import type { Observation } from "@/lib/types"

// Fictional / demo observation records. Not real Darukaa.Earth data.
export const observations: Observation[] = [
  {
    id: "obs-001",
    species: "Indian Gaur",
    siteId: "site-wg-04",
    siteName: "Site 04",
    observedDate: "2026-08-18",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.43, 13.76],
    category: "Mammal",
  },
  {
    id: "obs-002",
    species: "King Cobra",
    siteId: "site-wg-02",
    siteName: "Site 02",
    observedDate: "2026-08-12",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.26, 13.23],
    category: "Reptile",
  },
  {
    id: "obs-003",
    species: "Malabar Pied Hornbill",
    siteId: "site-wg-01",
    siteName: "Site 01",
    observedDate: "2026-08-09",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.1, 13.51],
    category: "Bird",
  },
  {
    id: "obs-004",
    species: "Lion-tailed Macaque",
    siteId: "site-wg-01",
    siteName: "Site 01",
    observedDate: "2026-08-04",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.08, 13.49],
    category: "Mammal",
  },
  {
    id: "obs-005",
    species: "Mugger Crocodile",
    siteId: "site-mg-01",
    siteName: "Site 01",
    observedDate: "2026-07-30",
    location: "Gujarat",
    source: "Demo Dataset",
    coordinates: [69.73, 22.49],
    category: "Reptile",
  },
  {
    id: "obs-006",
    species: "Greater Flamingo",
    siteId: "site-mg-02",
    siteName: "Site 02",
    observedDate: "2026-07-27",
    location: "Gujarat",
    source: "Demo Dataset",
    coordinates: [69.91, 22.33],
    category: "Bird",
  },
  {
    id: "obs-007",
    species: "Proboscis Monkey",
    siteId: "site-fr-01",
    siteName: "Site 01",
    observedDate: "2026-07-21",
    location: "Sabah",
    source: "Demo Dataset",
    coordinates: [117.36, 5.43],
    category: "Mammal",
  },
  {
    id: "obs-008",
    species: "Rhinoceros Hornbill",
    siteId: "site-fr-02",
    siteName: "Site 02",
    observedDate: "2026-07-15",
    location: "Sabah",
    source: "Demo Dataset",
    coordinates: [117.61, 5.29],
    category: "Bird",
  },
  {
    id: "obs-009",
    species: "Smooth-coated Otter",
    siteId: "site-wl-01",
    siteName: "Site 01",
    observedDate: "2026-07-11",
    location: "Assam",
    source: "Demo Dataset",
    coordinates: [91.66, 26.14],
    category: "Mammal",
  },
  {
    id: "obs-010",
    species: "Spot-billed Pelican",
    siteId: "site-wl-01",
    siteName: "Site 01",
    observedDate: "2026-07-06",
    location: "Assam",
    source: "Demo Dataset",
    coordinates: [91.64, 26.12],
    category: "Bird",
  },
  {
    id: "obs-011",
    species: "Malabar Gliding Frog",
    siteId: "site-wg-02",
    siteName: "Site 02",
    observedDate: "2026-06-28",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.24, 13.21],
    category: "Amphibian",
  },
  {
    id: "obs-012",
    species: "Nilgiri Tahr",
    siteId: "site-wg-04",
    siteName: "Site 04",
    observedDate: "2026-06-22",
    location: "Western Ghats",
    source: "Demo Dataset",
    coordinates: [75.41, 13.74],
    category: "Mammal",
  },
]

export const biodiversitySummary = {
  totalObservations: 12486,
  speciesObserved: 324,
  recentObservations: 186,
  observationTrend: 12, // percent
}
