import type { Project } from "@/lib/types"

// Illustrative demo data. Not real Darukaa.Earth statistics.
export const projects: Project[] = [
  {
    id: "prj-wghats",
    name: "Western Ghats Restoration",
    description:
      "Long-term forest restoration and monitoring across degraded slopes of the Western Ghats, tracking canopy recovery and biodiversity return.",
    type: "Carbon + Biodiversity",
    region: "India",
    location: "Karnataka, India",
    startDate: "2022-03-01",
    status: "Active",
    siteCount: 8,
    area: 12480,
    biodiversityObservations: 4820,
    monitoringSince: 2022,
    createdAt: "2022-03-01",
    updatedAt: "2026-08-27",
  },
  {
    id: "prj-mangrove",
    name: "Mangrove Conservation",
    description:
      "Coastal mangrove protection and blue-carbon monitoring across estuarine sites, tracking tidal vegetation health.",
    type: "Carbon",
    region: "India",
    location: "Gujarat, India",
    startDate: "2023-01-15",
    status: "Active",
    siteCount: 5,
    area: 4820,
    biodiversityObservations: 2140,
    monitoringSince: 2023,
    createdAt: "2023-01-15",
    updatedAt: "2026-08-24",
  },
  {
    id: "prj-forest-recovery",
    name: "Forest Recovery Initiative",
    description:
      "Regional reforestation program monitoring vegetation regrowth and species observations across tropical lowland sites.",
    type: "Carbon + Biodiversity",
    region: "Southeast Asia",
    location: "Sabah, Malaysia",
    startDate: "2021-06-10",
    status: "Monitoring",
    siteCount: 12,
    area: 18240,
    biodiversityObservations: 3960,
    monitoringSince: 2021,
    createdAt: "2021-06-10",
    updatedAt: "2026-08-20",
  },
  {
    id: "prj-wetland",
    name: "Wetland Monitoring Program",
    description:
      "Freshwater wetland ecological monitoring, tracking waterbird populations and seasonal vegetation dynamics.",
    type: "Biodiversity",
    region: "India",
    location: "Assam, India",
    startDate: "2024-02-20",
    status: "Monitoring",
    siteCount: 4,
    area: 6320,
    biodiversityObservations: 1180,
    monitoringSince: 2024,
    createdAt: "2024-02-20",
    updatedAt: "2026-08-15",
  },
  {
    id: "prj-grassland",
    name: "Grassland Carbon Baseline",
    description:
      "Baseline carbon and vegetation assessment across semi-arid grassland sites ahead of a restoration phase.",
    type: "Carbon",
    region: "India",
    location: "Maharashtra, India",
    startDate: "2026-05-05",
    status: "Draft",
    siteCount: 2,
    area: 2760,
    biodiversityObservations: 0,
    monitoringSince: 2026,
    createdAt: "2026-05-05",
    updatedAt: "2026-08-30",
  },
]
