import type { Site } from "@/lib/types"

// Build an irregular polygon ring around a center point (rough, illustrative).
function ring(lng: number, lat: number, r: number, seed = 1): [number, number][] {
  const pts: [number, number][] = []
  const n = 7
  for (let i = 0; i < n; i++) {
    const a = (i / n) * Math.PI * 2
    const jitter = 0.55 + ((Math.sin(seed * (i + 1) * 12.9898) * 43758.5453) % 1 + 1) / 2 * 0.7
    pts.push([
      +(lng + Math.cos(a) * r * jitter * 1.6).toFixed(4),
      +(lat + Math.sin(a) * r * jitter).toFixed(4),
    ])
  }
  pts.push(pts[0])
  return pts
}

// Illustrative demo data. Not real Darukaa.Earth statistics.
export const sites: Site[] = [
  {
    id: "site-wg-01",
    siteNumber: "Site 01",
    name: "Agumbe Ridge",
    projectId: "prj-wghats",
    projectName: "Western Ghats Restoration",
    location: "Western Ghats, India",
    region: "India",
    area: 1840,
    status: "Active",
    vegetationIndex: 0.78,
    biodiversityObservations: 964,
    monitoringPeriod: "2022–2026",
    createdAt: "2022-04-12",
    center: [75.09, 13.5],
    polygon: ring(75.09, 13.5, 0.06, 3),
  },
  {
    id: "site-wg-02",
    siteNumber: "Site 02",
    name: "Kudremukh Slopes",
    projectId: "prj-wghats",
    projectName: "Western Ghats Restoration",
    location: "Western Ghats, India",
    region: "India",
    area: 2210,
    status: "Active",
    vegetationIndex: 0.71,
    biodiversityObservations: 712,
    monitoringPeriod: "2022–2026",
    createdAt: "2022-05-03",
    center: [75.25, 13.22],
    polygon: ring(75.25, 13.22, 0.07, 7),
  },
  {
    id: "site-wg-04",
    siteNumber: "Site 04",
    name: "Western Ghats Restoration",
    projectId: "prj-wghats",
    projectName: "Western Ghats Restoration",
    location: "Western Ghats, India",
    region: "India",
    area: 1248,
    status: "Active",
    vegetationIndex: 0.72,
    biodiversityObservations: 842,
    monitoringPeriod: "2022–2026",
    createdAt: "2026-06-12",
    center: [75.42, 13.75],
    polygon: ring(75.42, 13.75, 0.05, 11),
  },
  {
    id: "site-mg-01",
    siteNumber: "Site 01",
    name: "Gulf of Kutch Mangrove",
    projectId: "prj-mangrove",
    projectName: "Mangrove Conservation",
    location: "Gujarat, India",
    region: "India",
    area: 980,
    status: "Active",
    vegetationIndex: 0.64,
    biodiversityObservations: 486,
    monitoringPeriod: "2023–2026",
    createdAt: "2023-02-01",
    center: [69.72, 22.48],
    polygon: ring(69.72, 22.48, 0.05, 5),
  },
  {
    id: "site-mg-02",
    siteNumber: "Site 02",
    name: "Estuary Belt",
    projectId: "prj-mangrove",
    projectName: "Mangrove Conservation",
    location: "Gujarat, India",
    region: "India",
    area: 1120,
    status: "Monitoring",
    vegetationIndex: 0.6,
    biodiversityObservations: 524,
    monitoringPeriod: "2023–2026",
    createdAt: "2023-03-18",
    center: [69.9, 22.32],
    polygon: ring(69.9, 22.32, 0.06, 9),
  },
  {
    id: "site-fr-01",
    siteNumber: "Site 01",
    name: "Lowland Recovery North",
    projectId: "prj-forest-recovery",
    projectName: "Forest Recovery Initiative",
    location: "Sabah, Malaysia",
    region: "Southeast Asia",
    area: 3120,
    status: "Monitoring",
    vegetationIndex: 0.69,
    biodiversityObservations: 1240,
    monitoringPeriod: "2021–2026",
    createdAt: "2021-07-01",
    center: [117.35, 5.42],
    polygon: ring(117.35, 5.42, 0.09, 4),
  },
  {
    id: "site-fr-02",
    siteNumber: "Site 02",
    name: "Riparian Corridor",
    projectId: "prj-forest-recovery",
    projectName: "Forest Recovery Initiative",
    location: "Sabah, Malaysia",
    region: "Southeast Asia",
    area: 2680,
    status: "Monitoring",
    vegetationIndex: 0.66,
    biodiversityObservations: 980,
    monitoringPeriod: "2021–2026",
    createdAt: "2021-09-14",
    center: [117.6, 5.28],
    polygon: ring(117.6, 5.28, 0.08, 8),
  },
  {
    id: "site-wl-01",
    siteNumber: "Site 01",
    name: "Deepor Wetland",
    projectId: "prj-wetland",
    projectName: "Wetland Monitoring Program",
    location: "Assam, India",
    region: "India",
    area: 1560,
    status: "Monitoring",
    vegetationIndex: 0.58,
    biodiversityObservations: 640,
    monitoringPeriod: "2024–2026",
    createdAt: "2024-03-01",
    center: [91.65, 26.13],
    polygon: ring(91.65, 26.13, 0.05, 6),
  },
]
